name: CI/CD pipeline
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Checking Code Quality
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.39.0
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          golangci-lint run --timeout 3m0s
        
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1.12

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: |
          mkdir build
          go test ./... -v -coverprofile build/coverage.txt -coverpkg=./...
          go tool cover -func build/coverage.txt

